# Help: `topgrade --config-reference` (displays https://github.com/topgrade-rs/topgrade/blob/main/config.example.toml)

[misc]
assume_yes = true
disable = ["containers", "git_repos", "pnpm", "yarn", "node"]
display_time = false
cleanup = true

[commands]
"npm" = "npm update --location global --force"
