# Don't ask for confirmations
assume_yes = true

# Disable specific steps - same options as the command line flag
disable = ["containers", "git_repos", "pnpm", "yarn"]

# Display the time in step titles
display_time = false

# Cleanup temporary or old files
cleanup = true
