name: Dotfiles Installation

on:
  push:
  schedule:
    - cron: '0 17 * * 4' # Every Thursday 5:00PM

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0, ubuntu-latest]

    steps:
      - name: Clean up installed software
        if: startsWith(matrix.os, 'macos')
        run: |
          brew uninstall --ignore-dependencies --force $(brew list --formula)
          # brew uninstall --cask --force $(brew list --cask)
          brew uninstall --cask --force firefox google-chrome
          brew cleanup --prune-prefix
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
          rm -rf "$NVM_DIR"

      - name: Download and install available system updates
        if: startsWith(matrix.os, 'macos')
        run: |
          sudo softwareupdate -i -a

      - name: Clone this repository
        uses: actions/checkout@v2

      - name: Install using Makefile
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            make
          else
            sudo make
          fi

      - name: Verify runcom setup
        run: source $HOME/.bash_profile

      - name: Run tests
        if: startsWith(matrix.os, 'macos')
        run: make test
